### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by RealyUniqueName**
- Removed `?` mark from optional arguments of basic types, because hxcpp converts such optional arguments to dynamics at runtime.
- Replaced `Lambda.indexOf()` with `Array.indexOf()` because own array's `indexOf()` is faster and with `Lambda.indexOf()` I experienced random crashes (didn't find out why).
- Added `Pathfinder.ignoreCachedPassability()` to support dynamic maps which can return different results of `map.isWalkable()` for the same node depending on third-party circumstances.
- Replaced  standard `Math` methods with custom implementations to accelerate calculations.

### CODE REVIEW

**Comment by hypersurge** [comment]
Very cool.  Thanks for the ? and Lambda.indexOf note - I did not know that, and will likely need to modify some other library signatures accordingly.

I will probably refactor the ignoreCachedPassability to make it a property on IMap (e.g. isDynamic, default of false).  Do you foresee any problems with that?

Also, is the optimization for sort considered best practise / has been tested?

**Comment by RealyUniqueName** [comment]
I made `ignoreCache` that way to avoid breaking compatibility wih existing code. Changing `IMap` signature will require to update existing code which uses library. But indeed, moving this setting to `IMap` is a better way.

As for `sort`, i removed `inline` since compiler won't inline it anyway because it's used as a callback.
`Std.int` was removed to reduce amount of function calls. 

I wrote some basic unit tests for this library and they all passed with these changes.

**Comment by RealyUniqueName** [comment]
Are you going to submit new version to haxelib?

**Comment by hypersurge** [comment]
Yes, just wrapping that up now - thanks.

**Comment by hypersurge** [comment]
Done (RC 0.2.18).  Please note slight changes to your pull request: p_isMapDynamic added as a parameter to createPath() (instead of ignoreCachedPassability()).

**Pull request merged**
